name: Release

on:
  push:
    branches:
      - main # 或者您想要侦听的任何其他分支

env:
  GITHUB_TOKEN: ${{ secrets.CLASH_TOKEN  }}

jobs:
  docker-build:
    name: Docker 打包、推送、登录服务器、执行命令
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 使用 v2 版本

      - name: Login to private Docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker build -t registry.cn-shanghai.aliyuncs.com/glinfen/glinfen-blog-data .

      # 推送Docker镜像到私有仓库
      - name: Push Docker image
        run: docker push registry.cn-shanghai.aliyuncs.com/glinfen/glinfen-blog-data

      - name: Build Docker image
        run: docker build -f ./.github/dockerfile  -t my-ssh-image .

      # 登录服务器
      - name: Setup SSH Key and Connect
        env:
          PRIVATE_KEY: ${{ secrets.ALY_SERVER_KEY }}
          SERVER: ${{ secrets.SERVER_ADDRESS }}
        run: |
          docker run --rm -e PRIVATE_KEY="$PRIVATE_KEY" -e SERVER="$SERVER" my-ssh-image
