name: Release

on:
  push:
    tags:
      - 'v*'

# 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
env:
  GITHUB_TOKEN: ${{ secrets.CLASH_TOKEN  }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npx changelogithub
