name: Release

on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.CLASH_TOKEN  }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 使用 v2 版本

      - name: Login to private Docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker build -t registry.cn-shanghai.aliyuncs.com/glinfen/glinfen-blog-data .

      # 推送Docker镜像到私有仓库
      - name: Push Docker image
        run: docker push registry.cn-shanghai.aliyuncs.com/glinfen/glinfen-blog-data

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npx changelogithub
